[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"
[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"
[[constraint]]
  name = "k8s.io/client-go"
  version = "v8.0.0"
[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"
