apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: secret-syncer
  namespace: secret-syncer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-syncer
subjects:
- kind: ServiceAccount
  name: secret-syncer
  namespace: secret-syncer
